CREATE DATABASE QLPHONGTIN
GO
USE QLPHONGTIN
GO
CREATE TABLE PHONGMAY 
(
	MAPHONG INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NAME NVARCHAR(100),
	SOMAY INT,
	STATUT NVARCHAR(100),
	GHICHU NTEXT
)
CREATE TABLE MONHOC 
(
	MAMON INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NAMESUBJECT NVARCHAR(100),
	GHICHU NTEXT
)
CREATE TABLE GIAOVIEN 
(
	MAGV INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NAME NVARCHAR(100),
	CHUYENMON NVARCHAR(100),
	GHICHU NTEXT
)
CREATE TABLE CLASS
(
	MALOP INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENLOP NVARCHAR(50),
	SOHOCSINH INT,
	GVCN NVARCHAR(100),
	GHICHU NTEXT
)
CREATE TABLE TIETHOC
(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MAMON INT FOREIGN KEY REFERENCES MONHOC(MAMON),
	MAGV INT FOREIGN KEY REFERENCES GIAOVIEN(MAGV),
	MAPHONG INT FOREIGN KEY REFERENCES PHONGMAY(MAPHONG),
	MALOP INT FOREIGN KEY REFERENCES CLASS(MALOP),
	TENBAI NVARCHAR(100),
	THOIGIAN DATE,
	TIET INT,
	TIETPPCT INT,
	GHICHU NTEXT
)
CREATE TABLE PCCP
(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	MAGV INT FOREIGN KEY REFERENCES GIAOVIEN(MAGV),
	MALOP INT FOREIGN KEY REFERENCES CLASS(MALOP)
)
DROP TABLE TIETHOC
